# nginx/docker-compose.yml
version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "5000:80"  # Optionally expose Nginx on host port 8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Use custom nginx.conf
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "64M"